# kubernetes-manifests/1_ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-store-ingress
  annotations:
    # Mandatory: Identifies the Ingress controller that should handle this resource
    kubernetes.io/ingress.class: alb
    # Mandatory: Creates an external-facing ALB
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Mandatory: Directs traffic to Pod IPs. Use 'instance' if using AWS Instance mode for NGs (not recommended).
    alb.ingress.kubernetes.io/target-type: ip
    # Highly Recommended: Redirect all HTTP traffic on port 80 to HTTPS on port 443
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # Optional but Good Practice: Specify the ALB type (application) and IP version (ipv4)
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=400
spec:
  rules:
  - host: Skillz008.onmicrosoft.com # Your domain here
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80
  tls:
  - hosts:
    - Skillz008.onmicrosoft.com
    # The secretName must be in the same namespace as the Ingress.
    # The AWS Load Balancer Controller will automatically handle the contents of this secret.
    secretName: innovatemart-tls-certificate
