name: Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      confirm_destroy:
        description: 'Confirm destruction'
        required: true
        type: boolean
        default: false

jobs:
  destroy:
    if: inputs.confirm_destroy == true
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
        
    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3
      
    - name: Setup Helm
      uses: azure/setup-helm@v3
      
    - name: Destroy Kubernetes resources
      run: |
        echo "Deleting Kubernetes resources..."
        kubectl delete -f kubernetes/ --ignore-not-found=true || true
        kubectl delete ingress retail-store-ingress --ignore-not-found=true || true
        helm uninstall aws-load-balancer-controller -n kube-system --ignore-not-found=true || true
        
    - name: Destroy Terraform infrastructure
      run: |
        echo "Destroying Terraform infrastructure..."
        cd terraform
        terraform init
        terraform destroy -auto-approve
        
    - name: Cleanup complete
      run: echo "✅ Cleanup completed successfully!"
