name: 'Terraform Plan'
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
