name: Destroy Infrastructure
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve
      env:
        # Database credentials (required for destroy to properly handle RDS)
        TF_VAR_rds_orders_username: ${{ secrets.RDS_ORDERS_USERNAME }}
        TF_VAR_rds_orders_password: ${{ secrets.RDS_ORDERS_PASSWORD }}
        TF_VAR_rds_catalog_username: ${{ secrets.RDS_CATALOG_USERNAME }}
        TF_VAR_rds_catalog_password: ${{ secrets.RDS_CATALOG_PASSWORD }}

    - name: Verify Destruction
      run: |
        echo "Infrastructure destruction completed successfully"
        echo "Destroyed resources include:"
        echo "- EKS Cluster: $(terraform output -raw cluster_name 2>/dev/null || echo 'Destroyed')"
        echo "- VPC and associated networking"
        echo "- RDS Databases (Orders and Catalog)"
        echo "- DynamoDB Table"
        echo "- Route53 Hosted Zone"
        echo "- ACM Certificate"
        echo "- IAM User and Policies"
