name: 'Terraform Apply'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'

      - name: Import existing AWS resources
        run: |
          terraform import aws_dynamodb_table.carts innovatemart-bedrock-Carts
          terraform import aws_iam_user.developer_ro innovatemart-bedrock-developer-ro
          terraform import aws_kms_alias.cluster arn:aws:kms:us-east-1:039367376953:alias/eks/innovatemart-bedrock-cluster
          terraform import aws_cloudwatch_log_group.this /aws/eks/innovatemart-bedrock-cluster/cluster
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 1: Apply only EKS cluster and dependencies
      - name: Terraform Apply (EKS only)
        run: terraform apply -target=aws_eks_cluster.main -auto-approve -input=false
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 2: Update kubeconfig so the kubernetes provider can connect
      - name: Configure kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name innovatemart-bedrock-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 3: Apply the rest of the Terraform resources
      - name: Terraform Apply (all resources)
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 4: Final convergence apply (fixes for_each dependency issues)
      - name: Terraform Apply (final convergence)
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
        env:
          TF_CLI_ARGS: '-no-color'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
